ToDoList/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todocore.urls"), name="todolist"),
]

todocore/urls.py
from django.urls import path

from todocore.views import (
    TagListView,
    TaskCreateView,
    TaskUpdateView,
    TagCreateView,
    TagUpdateView,
    TaskDeleteView,
    TaskListView,
    TagDeleteView,
    task_change_status,
)

urlpatterns = [
    path("", TaskListView.as_view(), name="index"),
    path("task/create/", TaskCreateView.as_view(), name="task-create"),
    path("task/<int:pk>/change-status/", task_change_status, name="task-change-status"),
    path("task/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("task/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tags/", TagListView.as_view(), name="tags-list"),
    path("tags/create/", TagCreateView.as_view(), name="tags-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tags-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tags-delete"),
]

todocore/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=40, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(blank=True, null=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks", blank=True, null=True)

    def __str__(self):
        return self.content

todocore/forms.py
from django import forms

from todocore.models import Task, Tag


class TaskForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(), widget=forms.CheckboxSelectMultiple, required=False
    )
    deadline = forms.SplitDateTimeField(
        widget=forms.SplitDateTimeWidget(
            date_attrs={"type": "date", "input_formats": ["%Y-%m-%d"]},
            time_attrs={"type": "time", "input_formats": ["%H:%M"]},
        ),
        required=False,
    )

    class Meta:
        model = Task
        fields = "__all__"

todocore/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    UpdateView,
    DeleteView,
    ListView
)

from todocore.forms import TaskForm
from todocore.models import Task, Tag


class TaskListView(ListView):
    model = Task
    ordering = ["is_done", "-datetime"]
    paginate_by = 8
    template_name = "todocore/index.html"


# def task_make_is_done(request, pk):
#     task = Task.objects.get(id=pk)
#     task.is_done = True
#     task.save()
#     return HttpResponseRedirect(reverse_lazy(viewname="index"))
#
#
# def task_make_is_not_dane(request, pk):
#     task = Task.objects.get(id=pk)
#     task.is_done = False
#     task.save()
#     return HttpResponseRedirect(reverse_lazy(viewname="index"))

def task_change_status(request, pk):
    task = Task.objects.get(id=pk)
    task.is_done = not task.is_done
    task.save()
    return HttpResponseRedirect(reverse_lazy(viewname="index"))


class TaskCreateView(CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("index")


class TaskUpdateView(UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("index")


class TaskDeleteView(DeleteView):
    model = Task
    success_url = reverse_lazy("index")


class TagCreateView(CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tags-list")


class TagUpdateView(UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tags-list")


class TagDeleteView(DeleteView):
    model = Tag
    success_url = reverse_lazy("tags-list")


class TagListView(ListView):
    model = Tag
    paginate_by = 8

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Team Task Manager</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <style>
        .sidebar {
            padding: 20px;
            height: 100vh;
        }
    </style>
</head>

<body>
    <div class="content-fluid">
        <div class="row">
            <div class="col-sm-2">
                <div class="sidebar">
                    {% block sidebar %}
                        {% include "includes/sidebar.html" %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-sm-10">
            <br>
                {% block content %}{% endblock %}
                {% block pagination %}
                    {% include "includes/pagination.html" %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% block sidebar %}
<div class="position-fixed">
    <div class="card">
        <div class="card-body">
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><a href="{% url 'index' %}" class="btn btn-outline-success btn-block">Home</a></li>
                <li class="list-group-item"><a href="{% url 'tags-list' %}" class="btn btn-outline-success btn-block">Tags</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

templates/todocore/index.html
{% extends "base.html" %}

{% block content %}
    <h1>
        TODO List
        <a class="btn btn-primary" href="{% url 'task-create' %}">Add task</a>
    </h1>
    <br>
    {% if task_list %}
        {% for task in task_list %}
            <div>
                <h4>{{ task }}</h4>{% if task.is_done %} <h4 style="color: green">Done!</h4>{% else %} <h4 style="color: red">Not Done!</h4>{% endif %}
                {% if task.is_done %}
                    <a href="{% url 'task-change-status' pk=task.id %}" class="btn btn-secondary">Undo</a>
                {% else %}
                    <a href="{% url 'task-change-status' pk=task.id %}" class="btn btn-success">Completed</a>
                {% endif %}
            </div>
    
            <br>
            <p>Created: {{ task.datetime }}</p> {% if task.deadline %}  <p style="color: red">Deadline: {{ task.deadline }}</p>{% endif %}
            <br>
            <h4 style="color: darkgray">
                Tags: {% for tag in task.tags.all %} {{ tag }}{% endfor %}
                <a href="{% url 'task-update' pk=task.id %}">Update</a>
                 <a href="{% url 'task-delete' pk=task.id %}">Delete</a>
            </h4>
            <br>
            <hr>
        {% endfor %}
    {% else %}
        <h3>No task in Your ToDo list!</h3>
    {% endif %}


{% endblock %}

templates/todocore/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "tags-list" %}">Cancel</a>
  </form>
{% endblock %}

templates/todocore/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}



{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todocore/tag_list.html
{% extends "base.html" %}

{% block content %}
    <h1>
        Tags
        <a class="btn btn-primary" href="{% url 'tags-create' %}">Add tag</a>
    </h1>
    <br>
    {% if tag_list %}
        <table class="table">
            <tr>
              <th>Name</th>
              <th>Update</th>
              <th>Delete</th>
            </tr>
        
            {% for tag in tag_list %}
                <tr>
                    <td>
                        {{ tag }}
                    </td>
                    <td>
                        <a class="btn btn-secondary" href="{% url 'tags-update' pk=tag.id %}"> Update</a>
                    </td>
                    <td>
                        <a class="btn btn-secondary" href="{% url 'tags-delete' pk=tag.id %}"> Delete</a>
                    </td>
                </tr>
                
            {% endfor %}
        </table>
    {% else %}
        <h3>No tags in tag list!</h3>
    {% endif %}


{% endblock %}

templates/todocore/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete Task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a class="btn btn-secondary" href="{% url "tags-list" %}">Cancel</a>
  </form>
{% endblock %}

templates/todocore/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}



{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}